kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  spec:
    type: NodePort
    selector:
      apps: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    apps: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      apps: train-schedule
      track: stable
  template:
    metadata:
      labels:
        apps: train-schedule
        track: stable
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
